version: '3'

services:
  app:
    env_file:
      - aws.env
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    ports:
      - 5001:5001
    volumes:
      - ~/.gitconfig:/root/.gitconfig
      - ~/.ssh:/root/.ssh-localhost:ro
      - ..:/workspace
    command: sleep infinity